### ISSUE TITLE
ORM Message Formatting on Robotics Request Console is Broken

### ISSUE THREAD

**Issue by blinkdog** [ScorpioStation/ScorpioStation#277]
**Issue Description**:
When the ORM sends an update message to the Robotics Request Console, the HTML formatting is broken.

**What did you expect to happen**:
The message should be formatted appropriately.

**What happened instead**:
The TGUI interface escaped the HTML codes as in-band, and it breaks the formatting of the message.

**Why is this bad/What are the consequences**:
The ORM update message looks a little weird.

**Steps to reproduce the problem**:
1. Mine some stuff
2. Turn in the minerals at the ORM
3. View messages on the Robotics Request Console

**Extra information**:
Usabaker provided this screenshot on Discord:
![](https://cdn.discordapp.com/attachments/728494917348753449/783130608842178560/unknown.png)

**Comment by Kiyahitayika** [comment]
Was this fixed by the upstream merge? I'm having difficulty reproducing the issue.

**Comment by blinkdog** [comment]
> Was this fixed by the upstream merge? I'm having difficulty reproducing the issue.

I believe so. I just triggered it and the HTML tags are gone.
The result still doesn't look great, but this issue can be closed.
